#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing fan controller...\n"
sudo cp fancontrol.py /usr/local/bin/
sudo chmod +x /usr/local/bin/fancontrol.py

echo "=> Starting fan controller...\n"
sudo cp fancontrol.service /lib/systemd/system/
sudo chmod 644 /lib/systemd/system/fancontrol.service

sudo systemctl daemon-reload
sudo systemctl enable fancontrol
sudo systemctl start fancontrol

echo "Fan controller installed."
